name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Runs when code is pushed to 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          echo "${{ secrets.SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Transfer Folder to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd /home/ubuntu/Diabites_Test_ML_Project || git clone https://github.com/NaveenShetter1/Diabites_Test_ML_Project.git
          cd /home/ubuntu/Diabites_Test_ML_Project
          git pull origin main
          EOF

      - name: Restart Flask App (main.py)
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            # Assuming you are using gunicorn or flask with systemd, restart the service
            sudo systemctl restart flaskapp  # Replace 'flaskapp' with the actual service name if different
          EOF

      - name: Verify Flask App Health Check
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            # Check if Flask app is running using health check endpoint
            curl -f http://localhost:5000/health || exit 1  # Adjust the port if necessary
          EOF
